### ISSUE TITLE
Non-linear points

### ISSUE THREAD

**Issue by wiscoDude** [southpolesteve/100-Day-Challenge#2]
Instead of our original count x value scoring, it seemed better to have a scoring system where you earned less points for each additional exercise.

One approach:

First 100 points of an activity are calculated by count x value
Next 100 points of that activity on that day are count x value/2 (twice as hard earning points with that exercise on that day)
etc

For example, if pushups are worth 2 points

And I do 300 pushups one day

50 x 2 = 100
100 x 1 = 100
150 x .5 = 75

So I would earn 275 points instead of 600 points from a linear system.

**Comment by southpolesteve** [comment]
Done.  Points are twice as hard every 100 points
